const Colorbox = document.getElementById("color-box")
const btn = document.getElementById("change-color-btn")
const text = document.getElementById("text")

    btn.addEventListener('click', ()=>{
        let a = Math.floor(Math.random()*255)
        let b = Math.floor(Math.random()*255)
        let c = Math.floor(Math.random()*255)
    let color = `rgb(${a},${b},${c})`;
    Colorbox.style.backgroundColor = color
    text.innerHTML = color
})

// i first call out the Elements with the dome call element just like in line 1,2 & 3.
// then i created a funtion that has to add an event listener to the button once click on by the user .
// of which i call out a variable call "color" and gave it a value of rgb color values as a,b,c as shown above. 
// i also generated a random number for each value of the rgb colors (a,b,c) using the Math.random so as to represent each rgb color code. 
// the Math.random attribute generates a random number ranging from 0 to 1 and convert it to a 3 set of arrays to represent each rgb color values of a,b,c. 
// the Math.floor atrribute picks the first random whole number generted by the Math.random() attribute  when mutiply by 255 . 
// then i use the "colorbox" as an id of the element i need to assign this function to and added a funtion to it to change the backgroundColor to which ever color is been generated by the rgb(a,b,c) as Color . 
// and lastly, i assign the text.innerHTML to display each set of the rgb numbers tha represent each color whn clicked on the button . 